[default]
description = "Default permissions for the plugin"
permissions = [
  "allow-create",
  "allow-load",
  "allow-save",
  "allow-delete",
  "allow-load-all",
  "allow-save-all",
  "allow-unlock",
]
