[default]
description = "Default permissions for the plugin"
permissions = [
  "allow-create",
  "allow-load",
  "allow-save",
  "allow-patch",
  "allow-delete",
  "allow-exists",
  "allow-load-all",
  "allow-save-all",
  "allow-patch-all",
  "allow-unlock",
  "allow-watch-file",
  "allow-unwatch-file",
  "allow-list-configs",
  "allow-reset",
  "allow-export-config",
  "allow-import-config",
]
